public enum BIRDTYPE {
    // BIRDS OF PREY

    HAWKS,    EAGLES,     OSPREY,
    // FLIGHTLESS BIRDS
    EMUS,    KIWIS,     MOAS,
    OWLS,
    // PARROTS
    ROSERINGPARAKEET,    GRAYPARROT,    SULFURCRESTEDCOCKATOO, // PARROTS

    //PIGEON
    PASSENGERPIGEON,//EXTINCT
    PIGEON,
    //SHORE BIRDS
    GREATAUK, CRESTEDAUKLET, HORNEDPUFFIN, AFRICANJACANA,
    // WATERFOWLS
    DUCKS, SWANS, GEESE







}
