public enum Birdtype {
  HAWKS, EAGLES, OSPREY, //Birds of Prey

  EMUS, KIWIS, MOAS,

  OWLS,

  ROSE_RING_PARAKEET, GRAY_PARROT, SULFUR_CRESTED_COCKATOO,

  PIGEONS, DOVES, EXTINCT_PIGEONS,

  GREAT_AUK, HORNED_PUFFIN, AFRICAN_JACANA,

  DUCKS, SWANS, GEESE
}