import java.util.ArrayList;
import java.util.List;

public enum LOCATION {
    LOCATION1, LOCATION2, LOCATION3, LOCATION4,
    LOCATION5,LOCATION6,LOCATION7,LOCATION8,
    LOCATION9, LOCATION10, LOCATION11,LOCATION12,
    LOCATION13,LOCATION14,LOCATION15,LOCATION16,LOCATION17,
    LOCATION18,LOCATION19,LOCATION20;



}

